apiVersion: v1
kind: Service
metadata:
  name: actix-web-demo-svc
  namespace: eks-example
  labels:
    app: actix-web-demo-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: actix-web-demo
